version: "3.8"

services:
  database:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=root

  php-apache:
    container_name: php-apache
    build:
      context: ./.docker/php/Dockerfile
      args:
        - PUID=${HOST_PUID}
        - PGID=${HOST_PGID}
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/desafio
      - ./.docker/apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
    depends_on:
      - database